;;; gdscript-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gdscript-comint.el

(register-definition-prefixes "gdscript-comint" '("gdscript-comint--" "godot-mode"))


;;; Generated autoloads from gdscript-comint-gdformat.el

(register-definition-prefixes "gdscript-comint-gdformat" '("gdformat-mode" "gdscript-comint-gdformat--"))


;;; Generated autoloads from gdscript-completion.el

(register-definition-prefixes "gdscript-completion" '("gdscript-completion-"))


;;; Generated autoloads from gdscript-customization.el

(register-definition-prefixes "gdscript-customization" '("gdscript-"))


;;; Generated autoloads from gdscript-debug.el

(autoload 'gdscript-debug-make-server "gdscript-debug" nil t)
(register-definition-prefixes "gdscript-debug" '("gdscript-"))


;;; Generated autoloads from gdscript-docs.el

(autoload 'gdscript-docs-browse-api "gdscript-docs" "\
Open the main page of Godot API. Use the universal prefix (C-u) to force browsing the online API.

(fn &optional FORCE-ONLINE)" t)
(register-definition-prefixes "gdscript-docs" '("gdscript-docs-"))


;;; Generated autoloads from gdscript-eglot.el

(let ((loads (get 'gdscript-eglot 'custom-loads))) (if (member '"gdscript-eglot" loads) nil (put 'gdscript-eglot 'custom-loads (cons '"gdscript-eglot" loads)) (put 'gdscript 'custom-loads (cons 'gdscript-eglot (get 'gdscript 'custom-loads)))))
(defvar gdscript-eglot-default-lsp-port 6005 "\
The default port for eglot to connect when extraction fails.")
(custom-autoload 'gdscript-eglot-default-lsp-port "gdscript-eglot" t)
(autoload 'gdscript-eglot-contact "gdscript-eglot" "\
Attempt to help `eglot' contact the running gdscript LSP.
Returns a list (HOST PORT) if successful, nil otherwise.  See the
last definition of CONTACT in `eglot-server-programs' for
definitions of HOST, PORT, and INTERACTIVE.

For more context, see
https://lists.gnu.org/archive/html/bug-gnu-emacs/2023-04/msg01070.html.

(fn INTERACTIVE)")
(register-definition-prefixes "gdscript-eglot" '("gdscript-eglot--extract-port"))


;;; Generated autoloads from gdscript-fill-paragraph.el

(register-definition-prefixes "gdscript-fill-paragraph" '("gdscript-fill-paragraph"))


;;; Generated autoloads from gdscript-format.el

(register-definition-prefixes "gdscript-format" '("gdscript-"))


;;; Generated autoloads from gdscript-godot.el

(let ((loads (get 'gdscript-godot 'custom-loads))) (if (member '"gdscript-godot" loads) nil (put 'gdscript-godot 'custom-loads (cons '"gdscript-godot" loads)) (put 'gdscript 'custom-loads (cons 'gdscript-godot (get 'gdscript 'custom-loads)))))
(defvar gdscript-godot-config-dir nil "\
The directory containing the Godot editor's configuration files.

If `gdscript-mode` is unable to find your config directory,
you may set this variable to an exact path.")
(custom-autoload 'gdscript-godot-config-dir "gdscript-godot" t)
(defvar gdscript-godot--debug-options-hydra :not-list)
(register-definition-prefixes "gdscript-godot" '("gdscript-godot-"))


;;; Generated autoloads from gdscript-history.el

(register-definition-prefixes "gdscript-history" '("gdscript-history--"))


;;; Generated autoloads from gdscript-hydra.el

(defvar gdscript-hydra--open nil)
(register-definition-prefixes "gdscript-hydra" '("gdscript-hydra-"))


;;; Generated autoloads from gdscript-imenu.el

(register-definition-prefixes "gdscript-imenu" '("gdscript-imenu-"))


;;; Generated autoloads from gdscript-indent-and-nav.el

(register-definition-prefixes "gdscript-indent-and-nav" '("gdscript-"))


;;; Generated autoloads from gdscript-keywords.el

(register-definition-prefixes "gdscript-keywords" '("gdscript-"))


;;; Generated autoloads from gdscript-mode.el

(add-to-list 'auto-mode-alist '("\\.gd\\'" . gdscript-mode))
(add-to-list 'auto-mode-alist '("\\.tscn\\'" . conf-toml-mode))
(add-to-list 'auto-mode-alist '("\\.tres\\'" . conf-toml-mode))
(with-eval-after-load 'eglot (defvar eglot-server-programs) (unless (equal (alist-get 'gdscript-mode eglot-server-programs) #'gdscript-eglot-contact) (push (cons 'gdscript-mode #'gdscript-eglot-contact) eglot-server-programs)))
(autoload 'gdscript-mode "gdscript-mode" "\
Major mode for editing Godot GDScript files.

(fn)" t)
(register-definition-prefixes "gdscript-mode" '("gdscript-"))


;;; Generated autoloads from gdscript-project.el

(register-definition-prefixes "gdscript-project" '("gdscript-project--"))


;;; Generated autoloads from gdscript-rx.el

(register-definition-prefixes "gdscript-rx" '("gdscript-rx"))


;;; Generated autoloads from gdscript-snippet.el

(register-definition-prefixes "gdscript-snippet" '("gdscript-snippet-"))


;;; Generated autoloads from gdscript-syntax.el

(register-definition-prefixes "gdscript-syntax" '("gdscript-"))


;;; Generated autoloads from gdscript-ts-mode.el

(autoload 'gdscript-ts-mode "gdscript-ts-mode" "\
Major mode for editing gdscript files, using tree-sitter library.

\\{gdscript-ts-mode-map}

(fn)" t)
(register-definition-prefixes "gdscript-ts-mode" '("gdscript-ts-"))


;;; Generated autoloads from gdscript-utils.el

(register-definition-prefixes "gdscript-utils" '("gdscript-"))

;;; End of scraped data

(provide 'gdscript-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gdscript-mode-autoloads.el ends here
